version: '1'

services:
  redis:
    container_name: TWB_redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    container_name: TWB_db
    image: "postgres:15.2"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres15_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres15_data: {}
